Update "Looking for libraries (packages)" Chapter
Modern-CMake-CN/Modern-CMake-zh_CN pull request #37
Opened 2023-01-04 12:38 UTC by xiaoweiChen

2023-01-04 16:31 UTC, zzsqwq requested changes

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/Boost.md
> +CMake 3.5 添加了导入目标。这些目标有助于处理依赖关系，所以这也是添加Boost库的好方法。然而，CMake 在所有已知版本的 Boost 中都包含依赖信息，因此 CMake 的版本必须比 Boost 新，这样CMake才能正常工作。最近 CMake 的 [合并请求][MROldBoost] 中，开始假设依赖项会从已知的上一个版本继承下来，并直接使用（同时给出警告）。这项功能也反向移植到
这里 “CMake 在所有已知版本的 Boost 中都包含依赖信息” 感觉有点不太合理，应该是 CMake 中包含了所有已知版本 Boost 库的依赖信息

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/CUDA.md
> +要检查 CUDA 是否可用，可使用checklanguage：
这里应该是 CheckLanguage，需要保持专业术语大小写的正确性。

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/CUDA.md
> +检查 `CMAKE_CUDA_COMPILER`（CMake 3.11 之前没有）查看 CUDA 开发包是否存在。
可以通过检查...，这样应该会贴切一些。

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/CUDA.md
> +构建CUDA代码时，应该以架构为目标。若没有也可以编译成PTX，nvcc编译器会提供了基本的指令，所以 PTX 还需要在运行时进行编译，这会使GPU kernel的加载速度慢得多。
“若没有也可以编译成PTX” 似乎不太合理，可能 “如果不这样做，也可以编译成 `ptx`” 会合理一些？

nvcc编译器会提供**了**基本的指令，多了一个了。

这段貌似增译了比较多，我不太懂 CUDA 这一块内容，能确保正确性应该就可以。

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/CUDA.md
> +可以用 `CUDA_NVCC_FLAGS`（使用列表添加的方式，`list(APPEND`）控制 CUDA 标志，通过`CUDA_SEPARABLE_COMPILATION` 控制分离编译。若想确保 CUDA 的正常工作，需要将关键字添加到目标中（CMake 3.9+）：
这里的标点有点问题

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/ROOT.md
> +可以通过`MODULE`参数，要求 ROOT 为执行相应的操作，而不是手动将生成的内容添加到库源代码中。此参数应该指定构建目标名：
这个位置的 **为** 是不是应该是 **来** 比较好

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/Minuit2.md
> +Minuit2 可以以标准的 方式使用 CMake，无论是使用 ROOT 源码，还是使用单独发行的源码包：
这个多了一个空格，以及是不是翻译成 ”Minuit2 可以以任何标准的 CMake 方式来引入“ 比较好

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/Minuit2.md
> +ROOT 案例中最困难的部分是，Minuit2 需要 `math/minuit2` 目录之外的文件。这个问题，通过使用`copy_standalone.cmake` 解决了。文件中使用一个函数，该函数接受一个文件名列表，然后返回原始源中的文件名列表；或者将文件复制到本地源中，并返回列表的新位置；亦或者，若原始源不存在（独立模式），则只返回列表的新位置。
returns a list of the new locations，这里应该说的是以列表的形式返回新的位置，而不是返回列表的新位置。后面的也是一样。

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/Minuit2.md
> +可以使用`make install` 或 `make package` （生成工件包），而无需从 ROOT 源内部或从独立发行包中添加 `standalone` 选项。
工件包？二进制包会不会更合适一些。

同时这句话 without adding this `standalone` option 修饰的是前面的，而不是后面的那一句，感觉这么翻译含义不太对。

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/OpenMP.md
> +CMake 3.9+ 中对 [OpenMP] 的支持进行了极大的改善。现代（TM）CMake 使用 OpenMP 的方法，可以直接将其添加到目标中：
可以直接将其添加到目标中感觉没必要有，这里直接说 “现代（TM）CMake 将 OpenMP 链接到一个目标的方法如下：” 即可。

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/ROOT.md
> +ROOT 提供了一个配置 ROOT 项目的[工具](https://root.cern.ch/how/integrate-root-my-project-cmake)，可以使用 `include("${ROOT_USE_FILE}")` 激活它。这将自动创建不美观的目录群和全局变量。这个工具的确可以节省一些配置时间，但若想在修改过程来解决一些棘手的问题，则需要花费大量的时间。若不需要创建库，那么
使用 macOS 操作系统时 这里漏译了一个 like，应该是例如使用 macOS 操作系统时，

2023-01-04 16:31 UTC, zzsqwq commented on chapters/packages/ROOT.md
> +ROOT 提供了  `rootpersist` 和 `genreflex`（`rootcling` 的遗留接口）二进制文件，这些二进制文件可生成构建字典所需的源文件，还定义了一个CMake函数`root_generate_dictionary`，其在构建过程中会使用 `rootling` 。
这里应该是 `rootcling` 而不是 `rootpersist`，看了一下最新版的原版也还是 `rootcling`，是原版这里写错了吗？

2023-01-05 04:38 UTC, xiaoweiChen commented on chapters/packages/Boost.md
> +CMake 3.5 添加了导入目标。这些目标有助于处理依赖关系，所以这也是添加Boost库的好方法。然而，CMake 在所有已知版本的 Boost 中都包含依赖信息，因此 CMake 的版本必须比 Boost 新，这样CMake才能正常工作。最近 CMake 的 [合并请求][MROldBoost] 中，开始假设依赖项会从已知的上一个版本继承下来，并直接使用（同时给出警告）。这项功能也反向移植到
嗯，的确。这里有点变扭。
你给出的译文会更好一些。

2023-01-05 04:56 UTC, xiaoweiChen commented on chapters/packages/CUDA.md
> +构建CUDA代码时，应该以架构为目标。若没有也可以编译成PTX，nvcc编译器会提供了基本的指令，所以 PTX 还需要在运行时进行编译，这会使GPU kernel的加载速度慢得多。
嗯，这里增加了一些内容，便于对GPU编程有个了解。

因为使用GPU的代码在编译方面，没有直接编译C/C++那么直观。GPU上所使用“可执行”文件其实需要相应的GPU编译器进行编译生成的。

CUDA的nvcc编译器比较特殊，这个编译器即编译原生C++代码，也可以编译CUDA的kernel代码。其背后的方式其实很简单，对于C/C++编译器进行了包装，在编译C/C++的时候会使用本地的C/C++编译器。而对于GPU kernel代码可以选择编译成PTX这种中间码表示(IR)，也可以直接指定相应的显卡能力版本，比如原文中的5.0、7.2这种，直接生成相应架构所使用的GPU可执行文件。

GPU的原生使用，就我所接触到的，都会比较复杂，也没有规范的统一过。而CUDA算是使用GPU做通用计算方面用起来比较简单的SDK了。

不过现在出现了很多库，会封装这些复杂的底层操作，所以使用起来会比较方便，比如用于机器学习的pytorch。

貌似说的有点多了，有兴趣可以去探索一下 :)

2023-01-05 04:59 UTC, xiaoweiChen commented on chapters/packages/CUDA.md
> +可以用 `CUDA_NVCC_FLAGS`（使用列表添加的方式，`list(APPEND`）控制 CUDA 标志，通过`CUDA_SEPARABLE_COMPILATION` 控制分离编译。若想确保 CUDA 的正常工作，需要将关键字添加到目标中（CMake 3.9+）：
是这里需要加空格么？
> 通过`CUDA_SEPARABLE_COMPILATION`

2023-01-05 05:04 UTC, xiaoweiChen commented on chapters/packages/Minuit2.md
> +Minuit2 可以以标准的 方式使用 CMake，无论是使用 ROOT 源码，还是使用单独发行的源码包：
en...

> 无论是使用 ROOT 源码，还是使用单独发行的源码包，Minuit2 都可以使用 CMake 的标准用法：

这样呢？

2023-01-05 05:07 UTC, zzsqwq commented on chapters/packages/CUDA.md
> +可以用 `CUDA_NVCC_FLAGS`（使用列表添加的方式，`list(APPEND`）控制 CUDA 标志，通过`CUDA_SEPARABLE_COMPILATION` 控制分离编译。若想确保 CUDA 的正常工作，需要将关键字添加到目标中（CMake 3.9+）：
空格这个我没注意到，貌似是少了一个），或者说多了一个（，（）没有闭合。

是想翻译成 （使用列表添加的方式，`list(APPEND)`），这样吗

2023-01-05 05:10 UTC, zzsqwq commented on chapters/packages/CUDA.md
> +构建CUDA代码时，应该以架构为目标。若没有也可以编译成PTX，nvcc编译器会提供了基本的指令，所以 PTX 还需要在运行时进行编译，这会使GPU kernel的加载速度慢得多。
wow 好赞👍🏻，有时间我也多去了解一下～ 所以这部分需要修改吗，这里他的原意是，可以编译到一个没有架构的平台上，还是说，可以选择不指定架构来编译？

2023-01-05 05:12 UTC, xiaoweiChen commented on chapters/packages/CUDA.md
> +可以用 `CUDA_NVCC_FLAGS`（使用列表添加的方式，`list(APPEND`）控制 CUDA 标志，通过`CUDA_SEPARABLE_COMPILATION` 控制分离编译。若想确保 CUDA 的正常工作，需要将关键字添加到目标中（CMake 3.9+）：
嗯，对的。想表达使用`list(APPEND)`的方式

2023-01-05 05:13 UTC, zzsqwq commented on chapters/packages/Minuit2.md
> +Minuit2 可以以标准的 方式使用 CMake，无论是使用 ROOT 源码，还是使用单独发行的源码包：
👍不错的！感觉这样比上面两个都要好。

2023-01-05 05:16 UTC, xiaoweiChen commented on chapters/packages/CUDA.md
> +构建CUDA代码时，应该以架构为目标。若没有也可以编译成PTX，nvcc编译器会提供了基本的指令，所以 PTX 还需要在运行时进行编译，这会使GPU kernel的加载速度慢得多。
这里是需要做一些调整，因为你指出来了，说明这段从你的角度来说，看不大太懂。

2023-01-05 05:31 UTC, xiaoweiChen commented on chapters/packages/ROOT.md
> +ROOT 提供了  `rootpersist` 和 `genreflex`（`rootcling` 的遗留接口）二进制文件，这些二进制文件可生成构建字典所需的源文件，还定义了一个CMake函数`root_generate_dictionary`，其在构建过程中会使用 `rootling` 。
o.0 .. 看做是手误吧

2023-01-05 06:58 UTC, zzsqwq approved these changes
👍非常棒的工作！LGTM.

2023-01-05 06:59 UTC, merged