Update basics.md
Modern-CMake-CN/Modern-CMake-zh_CN pull request #49
Opened 2024-07-18 09:15 UTC by Sunbuyu

改进了一些措辞上的细节，改善了上下文的连贯性，对一些没有模糊的描述做出进一步说明。

2024-07-18 09:39 UTC, zzsqwq requested changes

2024-07-18 09:39 UTC, zzsqwq commented on chapters/basics.md
> +«command:`target_link_libraries`» 可能是 CMake 中最有用也最令人迷惑的命令。这个命令需要指定一个目标 `another`，并且在给出该目标的名字后为此目标添加一个依赖关系。如果 CMake 项目中不存在名称为 `one` 的目标（没有定义该 target/目标），那它会直接添加名字为 `one` 的库到依赖中（一般而言，会去 `/usr`、CMake 项目
「It takes a target (another) and adds a dependency if a target is given.」 

这里我觉得翻译的不太对，这里想表达的含义应该是，如果目标 `another` 后跟了一个其他的目标名称（这里是 `one`），那么会把目标 `one` 链接到目标 `another`。在新的翻译中，该目标和此目标应该指的都是 `another`，这不太对。

「Or you can give it a full path to a library.」 这里应该没有因果关系？ 「或者你也可以填写库的完整路径，或者是链接器标志。」这样我觉得就还不错。

2024-07-28 09:16 UTC, Sunbuyu commented on chapters/basics.md
> +«command:`target_link_libraries`» 可能是 CMake 中最有用也最令人迷惑的命令。这个命令需要指定一个目标 `another`，并且在给出该目标的名字后为此目标添加一个依赖关系。如果 CMake 项目中不存在名称为 `one` 的目标（没有定义该 target/目标），那它会直接添加名字为 `one` 的库到依赖中（一般而言，会去 `/usr`、CMake 项目
> It takes a target (another) and adds a dependency if a target is given. 

此处确有不妥，感谢指正。

> Or you can give it a full path to a library. 

这里主要是考虑到前文直接给 `one` 的库名字但是没有给库的完整路径，和前文衔接的考虑加上了因果关系，但是和后句的连接器标志这里内容的衔接也有点勉强。看起来需要重新改一下。

2024-07-28 09:35 UTC, Sunbuyu commented on chapters/basics.md
> +«command:`target_link_libraries`» 可能是 CMake 中最有用也最令人迷惑的命令。这个命令需要指定一个目标 `another`，并且在给出该目标的名字后为此目标添加一个依赖关系。如果 CMake 项目中不存在名称为 `one` 的目标（没有定义该 target/目标），那它会直接添加名字为 `one` 的库到依赖中（一般而言，会去 `/usr`、CMake 项目
已经修改在pr中

2024-08-06 03:36 UTC, zzsqwq approved these changes

2024-08-06 03:36 UTC, merged

2024-08-06 03:36 UTC, zzsqwq commented
感谢贡献！